     - name: Adding user to admin group in cluster "{{ PIS_Cluster }}"
       community.vmware.vmware_object_role_permission:
        hostname: "{{ inventory_hostname }}"
        username: "{{ esxi_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        object_name: rootFolder
        role: Administrator
        principal: c88648
        state: present